item1_locator = "//*[@alt='Radiant Tee']"
item1_size_locator = "(//*[@option-id='167' and @aria-checked='false'])[1]"
item1_color_locator = "(//*[@option-id='50' and @aria-checked='false'])[1]"
item1_img_locator = "(//*[@class='product-image-photo'])[1]"
item1_add_locator = "//button[@class='action tocart primary']"
cart_counter_locator = "//span[@class='counter-number']"
cart_locator = "//*[@class='minicart-wrapper']"
cart_top_locator = "//button[@id='top-cart-btn-checkout']"
email_locator = "//div[@class='control _with-tooltip']/input[@name='username']"
firstname_locator = "//*[@name='firstname']"
lastname_locator = "//*[@name='lastname']"
company_locator = "//*[@name='company']"
adress_locator = "//*[@name='street[0]']"
city_locator = "//*[@name='city']"
region_locator = "//*[@name='region_id']"
postcode_locator = "//*[@name='postcode']"
phone_locator = "//*[@name='telephone']"
shipping_locator = "//*[@value='flatrate_flatrate']"
next_button_locator = "//*[@class='button action continue primary']"
loading_mask_locator = "//*[@class='loading-mask']"
place_order_locator = "//*[contains(text(), 'Place Order')]"
cookie_accept_button_locator = "//*[@aria-label='Consent']/p"