item1_locator = "//*[@alt='Radiant Tee']"
item1_size_locator = "(//*[@option-id='167' and @aria-checked='false'])[1]"
item1_size_from_product_locator = "//*[@option-id='167' and @aria-checked='false']"
item1_xssize_from_product_locator = "//*[@option-id='166' and @aria-checked='false']"
item1_color_locator_from_product_locator = "//*[@option-id='50' and @aria-checked='false']"
item1_quantity_locator = "//*[@id='qty']"
quantity_error_locator = "//*[@id='qty-error']"
stock_error_locator = "//*[contains(text(),'The requested qty is not available')]"
item1_add_from_product_locator = "//*[@id='product-addtocart-button']"
item1_color_locator = "(//*[@option-id='50' and @aria-checked='false'])[1]"
item1_img_locator = "(//*[@class='product-image-photo'])[1]"
item1_add_locator = "//button[@class='action tocart primary']"
cart_counter_locator = "//span[@class='counter-number']"
cart_locator = "//*[@class='minicart-wrapper']"
cart_top_locator = "//button[@id='top-cart-btn-checkout']"
email_locator = "//div[@class='control _with-tooltip']/input[@name='username']"
firstname_locator = "//*[@name='firstname']"
lastname_locator = "//*[@name='lastname']"
company_locator = "//*[@name='company']"
address_locator = "//*[@name='street[0]']"
city_locator = "//*[@name='city']"
region_locator = "//*[@name='region_id']"
postcode_locator = "//*[@name='postcode']"
phone_locator = "//*[@name='telephone']"
shipping_locator = "//*[@value='flatrate_flatrate']"
next_button_locator = "//*[@class='button action continue primary']"
loading_mask_locator = "//*[@class='loading-mask']"
place_order_locator = "//*[contains(text(), 'Place Order')]"
email_error_locator = "//*[@id='customer-email-error']"
shipping_error_locator = "//span[@data-bind='text: errorValidationMessage()']"
firstname_error_locator = "//input[@name='firstname']/following-sibling::div[starts-with(@id, 'error-')]"
lastname_error_locator = "//input[@name='lastname']/following-sibling::div[starts-with(@id, 'error-')]"
address_error_locator = "//input[@name='street[0]']/following-sibling::div[starts-with(@id, 'error-')]"
city_error_locator = "//input[@name='city']/following-sibling::div[starts-with(@id, 'error-')]"
state_error_locator = "//select[@name='region_id']/following-sibling::div[starts-with(@id, 'error-')]"
postcode_error_locator = "//input[@name='postcode']/following-sibling::div[starts-with(@id, 'error-')]"
phone_error_locator = "//input[@name='telephone']/following-sibling::div[starts-with(@id, 'error-')]"
cookie_accept_button_locator = "//*[@aria-label='Consent']/p"